## Load data

In [2]:
import numpy as np
import pandas as pd
import json
from dataclasses import dataclass

def load_json_dict(filename):
    # Open a file in read mode ('r')
    with open(f'{filename}.json', 'r') as json_file:
        # Use json.load() to read the data and convert it back to a dictionary
        return json.load(json_file)
    
def get_model_metadata(model_id):
    return model_metadatas[str(model_id)]

def get_model_data(model_id):
    return model_datas[str(model_id)]

def get_model_diet_data(model_id):
    return model_diet_datas[str(model_id)]

model_metadatas = load_json_dict('model_metadatas')
model_datas = load_json_dict('model_datas')
model_diet_datas = load_json_dict('model_diet_datas')

In [ ]:
@dataclass
class SpeciesGroup:
    group_name: str
    group_seq: int
    model_number: int
    model_name: str
    model_country: str
    model_year: str
    lme: int
    tl: float
    biomass: float
    pb: float
    qb: float
    ee: float
    M0b: float
    flow_to_det: float
    gross_efficiency: float
    prop_unassimilated_food: float
    respiration: float
    biomass_accum: float
    biomass_accum_rate: float
    immigration: float
    emigration: float
    export: float
    trophic_info: str
    detritus_import: float
    taxons_included: list[dict] 

    @classmethod
    def from_dict(cls, data: dict):
        """Factory method to create an instance from a dictionary."""
        return cls(**data)

    def __str__(self):
        return f"[{self.model_number}] '{self.model_name}' {self.model_country} ({self.model_year}) -> {self.group_seq}: {self.group_name} | tl: {self.tl}, taxons included: {[self.taxons_included[i]['taxon_name'] + ' (' + self.taxons_included[i]['AphiaID'] + ')' for i in range(len(self.taxons_included))]}"
    
    def to_df_row(self):
        dct = self.__dict__.copy()
        dct.pop("taxons_included")
        return pd.DataFrame(dct)

def decoder(dct):
    return SpeciesGroup.from_dict(dct)

def read_json_SpeciesGroup_list(filename):
    # Open the JSON file and load the data
    with open(f'{filename}.json', 'r') as f:
        # Use json.load and specify the object_hook
        return json.load(f, object_hook=decoder)
    
species_groups = read_json_SpeciesGroup_list("SpeciesGroups")

### functions to get information on specific model

In [4]:
def get_model_groups_data(model_number):
    def to_df_row(c: SpeciesGroup):
        dct = c.__dict__.copy()
        dct.pop("taxons_included")
        return pd.DataFrame([dct])

    df_rows = [to_df_row(species_groups[i]) for i in range(len(species_groups)) if species_groups[i].model_number == model_number]
    df = pd.concat(df_rows, ignore_index=True)
    df = df.replace("-9999", np.nan).replace(-9999, np.nan)

    df = df.rename(columns={  # change names
        'export': 'catch',
        'prop_unassimilated_food': 'gs',
        'gross_efficiency': 'ge'
        })
    
    df['p'] = df['pb'] * df['biomass']  # production
    df['q'] = df['qb'] * df['biomass']  # consumption
    df['M0'] = df['p'] * (1-df['ee'])  # other mortality
    df['net_migration'] = df['emigration'] - df['immigration']  # net migration
    
      # production*EE = catch + predation + biomass_accum + net_migration:
    df['predation'] = df['p'] * df['ee'] - (df['catch'] + df['biomass_accum'] + df['net_migration'])
    df['egestion'] = df['q'] * df['gs']  # gs

    df['flow_to_det'] = df['egestion'] + df['M0']

    cols_to_return = ['group_name', 'trophic_info', 'tl', 'ge', 'ee', 'catch', 
        'biomass', 'pb', 'qb', 'p', 'q', 'predation', 'M0', 'gs', 'egestion', 'respiration', 'biomass_accum', 'emigration', 'immigration', 'net_migration',
         'flow_to_det', 'detritus_import',        
        ]

    return df.set_index('group_seq')[cols_to_return]

def get_seq2name(model_number):
    model = get_model_diet_data(model_number)
    if not isinstance(model, dict):
        return None
    
    groups = model.get('group', {})
    if len(groups) == 0:
        return None
    
    return {int(g["group_seq"]): g["group_name"] for g in groups}

def get_DC(model_number):
    model = get_model_diet_data(model_number)
    if not isinstance(model, dict):
        return None
    
    groups = model.get('group', {})
    if len(groups) == 0:
        return None
    
    n = len(groups)
    
    DC_dict = {}
    detritus_fate_dict = {}

    for g in groups:
        diet_descr = g.get('diet_descr', {})
        diet_descr = diet_descr if diet_descr else {}
        diet = diet_descr.get('diet', None)
        if not diet:
            DC_dict[int(g['group_seq'])] = {int(g['group_seq']): None}
            detritus_fate_dict[int(g['group_seq'])] = {int(g['group_seq']): None}
        else:
            diet = diet if isinstance(diet, list) else [diet]
            DC_dict[int(g['group_seq'])] = {int(d['prey_seq']): float(d['proportion']) for d in diet}
            detritus_fate_dict[int(g['group_seq'])] = {int(d['prey_seq']): float(d['detritus_fate']) for d in diet}
    
    # add missing columns:
    DC = pd.DataFrame.from_dict(DC_dict, orient='index').fillna(0)
    for g in groups:
        if int(g['group_seq']) not in DC.columns:
            DC[int(g['group_seq'])] = 0

    DC = DC.sort_index().sort_index(axis=1)

    detritus_fate = pd.DataFrame.from_dict(detritus_fate_dict, orient='index').fillna(0)
    detritus_fate = detritus_fate.sort_index().sort_index(axis=1)

    return DC, detritus_fate

# Implementation

In [5]:
model_number = 227  # Iceland

# general data:
seq2name = get_seq2name(model_number)
groups_data = get_model_groups_data(model_number).fillna(0)

# DC and detritus_fate matrices:
DC, det_fate = get_DC(model_number)

Z = DC.mul(groups_data['q'], axis='index')
DET_seq = list(groups_data[groups_data['trophic_info'] == 'DET'].index.values)
if len(DET_seq) == 1:
    Z.loc[DET_seq[0], :] = groups_data['flow_to_det']
elif len(DET_seq) == 2:  # det_date acts as a switch between DET groups
    Z.loc[DET_seq[0], :] = groups_data['flow_to_det'] * (DC * (1-det_fate)).sum(axis=1)
    Z.loc[DET_seq[1], :] = groups_data['flow_to_det'] * (DC * (det_fate)).sum(axis=1)
else:
    raise Exception('too many detritus groups(?)')

production = groups_data['p'].copy()

# combine PP to single row:
PP_seq_list = sorted(groups_data.index[groups_data['trophic_info'] == 'PP'].values)
PP_seq = PP_seq_list[-1]
seq_to_drop = PP_seq_list[:-1]
if len(PP_seq_list) > 1:

    production.loc[PP_seq] += production.loc[seq_to_drop].sum()
    production = production.drop(index=seq_to_drop)

    Z.loc[:, PP_seq] += Z.loc[:, seq_to_drop].sum(axis=1)
    Z = Z.drop(index=seq_to_drop, columns=seq_to_drop)

# combine part of DET that is PP into PP row:
DET_seq = groups_data[groups_data['trophic_info'] == 'DET'].index.values[0]
Z_without_DET = Z.copy()
percent_of_det_that_is_PP = Z_without_DET.loc[DET_seq, PP_seq] / Z_without_DET.loc[DET_seq, :].sum()  # 98%
Z_without_DET.loc[:, PP_seq] += percent_of_det_that_is_PP * Z_without_DET.loc[:, DET_seq]
Z_without_DET = Z_without_DET.drop(index=DET_seq, columns=DET_seq)

# production of living compartments:
new_index = Z_without_DET.index
P = production[new_index].copy()
ee = groups_data.loc[new_index, "ee"]
non_PP = groups_data['trophic_info'] == 'Regular'
P[non_PP] = P[non_PP].mul(ee[non_PP])   # P*EE = (export + predation + growth + net_migration), without M0
# EE = (export + predation + growth + net_migration) / (export + predation + growth + net_migration + M0)
P = P.sort_index(ascending=False)

# production-normalized transaction matrix:
A = Z_without_DET.T.sort_index(ascending=False).sort_index(axis=1, ascending=False) / P
A = A.rename(index=seq2name, columns=seq2name)

# production requirement matrix:
seq_to_drop = P.index[P == 0]
A = A.drop(columns=seq_to_drop, index=seq_to_drop)
L = pd.DataFrame(np.linalg.inv((np.identity(A.shape[0]) - A)), index=A.index, columns=A.columns)

L

,Phytoplankton,Zooplankton,Other Fish,Benthos,Molluscs,Northern Shrimp,Nephrops,Other Pelagics,Capelin,Herring,...,Greenland Halibut,Redfish,Saithe,Haddock,Juvenile Cod,Adult Cod,Seabirds,Pinnipeds,Baleen whales,Toothed whales
Phytoplankton,1.0,3.57432,55.776089,21.959211,146.944117,45.799731,45.117829,66.262510,17.457306,17.356974,...,598.543183,5.782683e+01,1.294161e+02,9.598161e+01,73.132026,203.561990,4435.944206,45547.052511,4929.048340,350307.199244
Zooplankton,0.0,1.00000,8.720015,0.000000,16.822295,2.894737,2.631579,7.726950,4.736842,4.709618,...,70.191237,7.621788e+00,2.193759e+01,5.938570e+00,4.612672,25.300662,633.395302,5387.600280,717.094056,42276.630708
Other Fish,0.0,0.00000,1.074024,0.000000,1.683056,0.000000,0.000000,0.138745,0.000000,0.000000,...,4.388946,2.476570e-01,1.506263e+00,1.285835e-01,0.263795,1.216444,11.627126,315.606664,28.784070,2516.021891
Benthos,0.0,0.00000,1.120167,1.000000,3.858830,1.578947,1.578947,1.759545,0.000000,0.000000,...,15.603387,1.385514e+00,2.283310e+00,3.384323e+00,2.544750,5.068848,95.688767,1176.298495,105.848862,8902.318808
Molluscs,0.0,0.00000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.400221,5.485752e-19,-1.172908e-20,-7.141261e-21,0.000000,0.037513,0.000000,61.807871,4.776354,656.839054
Northern Shrimp,0.0,0.00000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,1.312793,8.227147e-02,2.008450e-02,1.950284e-01,0.526316,0.779348,0.000000,100.795178,8.816625,615.256361
Nephrops,0.0,0.00000,0.000000,0.000000,0.008903,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.008027,1.362139e-20,-2.912387e-22,-1.773210e-22,0.000000,0.000876,0.000000,1.706375,1.313530,31.710923
Other Pelagics,0.0,0.00000,0.696406,0.000000,1.091307,0.000000,0.000000,1.305284,0.000000,0.000000,...,3.874144,2.885112e-01,9.904810e-01,8.708577e-02,0.171047,1.201584,11.995948,259.298257,24.063325,2004.792103
Capelin,0.0,0.00000,0.005730,0.000000,0.008980,0.000000,0.000000,0.000740,1.000000,0.000000,...,3.560681,1.592161e-01,1.573959e+00,5.397352e-01,0.001407,1.813784,103.582251,301.603513,25.104365,2273.152871
Herring,0.0,0.00000,0.013312,0.000000,0.020860,0.000000,0.000000,0.010146,0.000000,1.000000,...,0.074976,3.956510e-03,2.402800e-02,1.619435e-03,0.003270,0.047447,1.469014,54.300563,10.348078,353.916118
Other Dem. Fish,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.271651,2.488900e-18,-5.321514e-20,-3.240008e-20,0.000000,0.154434,0.000000,44.027689,4.388806,281.887798
Other Flatfish,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.072720,3.332434e-18,1.246538e-02,3.684210e-02,0.000000,0.159555,0.000000,22.976871,2.309475,147.411704
Greenland Halibut,-0.0,-0.00000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,1.464347,-0.000000e+00,-0.000000e+00,-0.000000e+00,-0.000000,0.042423,-0.000000,27.141748,2.705567,173.775364
Redfish,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.456981,1.000000e+00,5.793583e-02,2.901032e-02,0.000000,0.173197,0.000000,43.363678,7.590229,350.612767
Saithe,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012908,5.915172e-19,1.000000e+00,-7.700272e-21,0.000000,0.028321,0.000000,18.755199,1.869572,120.080381
Haddock,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.009229,4.229028e-19,5.263158e-02,1.000000e+00,0.000000,0.020248,0.000000,14.291422,1.942358,99.698489
Juvenile Cod,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.423137,2.631579e-02,7.533323e-03,2.966905e-03,1.000000,0.061748,0.000000,29.641030,3.041834,191.715537
Adult Cod,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.463863,2.125677e-17,-4.544908e-19,-2.767171e-19,0.000000,1.017759,0.000000,27.343625,2.725691,175.067881
Seabirds,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,1.000000,1.050761,0.000000,9.893354
Pinnipeds,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,1.380349,0.000000,6.659127
Baleen whales,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.125803,1.000000,5.431139
Toothed whales,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,2.002649

In [11]:
L.loc[[seq2name[PP_seq]], :]

,Phytoplankton,Zooplankton,Other Fish,Benthos,Molluscs,Northern Shrimp,Nephrops,Other Pelagics,Capelin,Herring,...,Greenland Halibut,Redfish,Saithe,Haddock,Juvenile Cod,Adult Cod,Seabirds,Pinnipeds,Baleen whales,Toothed whales
Phytoplankton,1.0,3.57432,55.776089,21.959211,146.944117,45.799731,45.117829,66.26251,17.457306,17.356974,...,598.543183,57.826826,129.416118,95.981615,73.132026,203.56199,4435.944206,45547.052511,4929.04834,350307.199244

In [1]:
from SPPR_2015 import *

SPPR, seq2name, DC, Z, P, A, L, groups_data, PP_seq, DET_seq, new_index = SPPR_2015(model_number=227)  # Iceland 1950

SPPR.rename(index=seq2name)

Phytoplankton             1.000000
Zooplankton               3.574320
Other Fish               55.776089
Benthos                  21.959211
Molluscs                146.944117
Northern Shrimp          45.799731
Nephrops                 45.117829
Other Pelagics           66.262510
Capelin                  17.457306
Herring                  17.356974
Other Dem. Fish         230.735659
Other Flatfish          171.268168
Greenland Halibut       598.543183
Redfish                  57.826826
Saithe                  129.416118
Haddock                  95.981615
Juvenile Cod             73.132026
Adult Cod               203.561990
Seabirds               4435.944206
Pinnipeds             45547.052511
Baleen whales          4929.048340
Toothed whales       350307.199244
Name: 23, dtype: float64

In [8]:
# P.sort_index(ascending=False).sort_index(ascending=False, axis=1).rename(index=seq2name, columns=seq2name)
P.sort_index(ascending=False).rename(index=seq2name)

Phytoplankton        17243.892518
Zooplankton            101.798436
Other Fish               5.192891
Benthos                 19.406477
Molluscs                 0.831379
Northern Shrimp          1.742974
Nephrops                 0.082723
Other Pelagics           4.355170
Capelin                  5.189411
Herring                  1.014292
Other Dem. Fish          0.680416
Other Flatfish           0.437523
Greenland Halibut        0.313843
Redfish                  1.170128
Saithe                   0.387632
Haddock                  0.374264
Juvenile Cod             0.382883
Adult Cod                1.172191
Seabirds                 0.008827
Pinnipeds                0.006611
Baleen whales            0.046074
Toothed whales           0.001575
Name: p, dtype: float64

### In the Article, They used TE instead of GE (should use GE):

In [5]:
catch = groups_data['catch']
predation = Z_without_DET.sum(axis=0).sort_index(ascending=False)
growth = groups_data['biomass_accum']
net_migration = groups_data['net_migration']
M0 = groups_data['M0']
# p = catch + predation + growth + net_migration + M0

q = Z_without_DET.sum(axis=1).sort_index(ascending=False)
ge_times_ee = groups_data['p'] * groups_data['ee'] / q   # This is what was used in 2015

df = pd.DataFrame({
    'ge': groups_data['ge'].round(decimals=6),
    'ge_calc': ((catch + predation + growth + net_migration + M0) / q).round(decimals=6),
    'ge*ee': ge_times_ee.round(decimals=6),
    'te_calc': ((catch + predation + growth + net_migration) / q).round(decimals=6),
    'ee': groups_data['ee'],
    'ee_calc': ((catch + predation + growth + net_migration) / (catch + predation + growth + net_migration + M0)).round(decimals=6)
})
df.sort_index(ascending=False).rename(index=seq2name)

                         ge   ge_calc     ge*ee   te_calc        ee   ee_calc
Detritus           0.000000       NaN       NaN       NaN  0.017924       NaN
Phytoplankton      0.000000       inf       inf       inf  0.400000  0.591069
Benthic producers  0.000000       NaN       NaN       NaN  0.007927       NaN
Zooplankton        0.294498  0.294498  0.279773  0.279773  0.950000  0.950000
Other Fish         0.200000  0.200000  0.190000  0.190000  0.950000  0.950000
Benthos            0.090000  0.091078  0.045539  0.045539  0.500000  0.500000
Molluscs           0.150000  0.150599  0.112949  0.112949  0.750000  0.750000
Northern Shrimp    0.200000  0.200339  0.190322  0.190322  0.950000  0.950000
Nephrops           0.200000  0.200509  0.190483  0.190483  0.950000  0.950000
Other Pelagics     0.150000  0.150000  0.142500  0.142500  0.950000  0.950000
Capelin            0.200000  0.200000  0.190000  0.190000  0.950000  0.950000
Herring            0.201156  0.201156  0.191098  0.191098  0.950000  0.950000
Other Dem. Fish    0.150000  0.150319  0.142803  0.142803  0.950000  0.950000
Other Flatfish     0.200000  0.200000  0.190000  0.190000  0.950000  0.950000
Greenland Halibut  0.200000  0.200000  0.190000  0.190000  0.950000  0.950000
Redfish            0.200000  0.200000  0.190000  0.190000  0.950000  0.950000
Saithe             0.200000  0.200003  0.190003  0.190003  0.950000  0.950000
Haddock            0.200000  0.200000  0.190000  0.190000  0.950000  0.950000
Juvenile Cod       0.300000  0.300000  0.285000  0.285000  0.950000  0.950000
Adult Cod          0.200000  0.200000  0.190000  0.190000  0.950000  0.950000
Seabirds           0.004566  0.004571  0.004343  0.004343  0.950000  0.950000
Pinnipeds          0.003510  0.003510  0.003334  0.003334  0.950000  0.950000
Baleen whales      0.004211  0.004211  0.004000  0.004000  0.950000  0.950000
Toothed whales     0.003155  0.003155  0.002997  0.002997  0.950000  0.950000

In [111]:
model_number = 227

seq2name = get_seq2name(model_number)
name2seq = {v: k for k, v in seq2name.items()}
model_groups_data = get_model_groups_data(model_number).fillna(0)
DC, det_fate = get_DC(model_number)
Z = DC.mul(model_groups_data['q'], axis='index')
DC = DC.sort_index(ascending=False).rename(index=seq2name)
Z = Z.sort_index(ascending=False).sort_index(axis=1, ascending=False).rename(index=seq2name, columns=seq2name)
model_groups_data = model_groups_data.sort_index(ascending=False).rename(index=seq2name)
det_fate = det_fate.sort_index(ascending=False).rename(index=seq2name)

ee = model_groups_data['ee']
biomass = model_groups_data['biomass']
ge = model_groups_data['gross_efficiency']  # te
gs = model_groups_data['prop_unassimilated_food']  # te
p = model_groups_data['biomass'] * model_groups_data['pb']
q = model_groups_data['biomass'] * model_groups_data['qb']
p_times_ee = p * ee
predation = Z.sum(axis=0)
inner_q = Z.sum(axis=1)
M0 = model_groups_data['biomass'] * model_groups_data['pb'] * (1-model_groups_data['ee'])
# M0 = model_groups_data['biomass'] * model_groups_data['pb']
export = model_groups_data['export']
growth = model_groups_data['biomass_accum']
net_migration = + model_groups_data['emigration'] - model_groups_data['immigration']
egestion = model_groups_data["biomass"] * model_groups_data["qb"] * (model_groups_data["prop_unassimilated_food"]) * (DC * (1-det_fate)).sum(axis=1)
respiration = model_groups_data['respiration']

# q[non_det] = inner_q[non_det]
# growth[det] + predation[det] = inner_q[det]

df = pd.DataFrame({
    # 'biomass': biomass,
    'q': q,
    'p': p,
    'test': q - (p + egestion + respiration),  # should be 0
    'test3': p - (predation + M0 + growth + net_migration + export),  # should be 0 (definition of P)
    'test4': p_times_ee - (export + predation +  growth + net_migration),  # should be 0 (definition of EE)
    'predation': predation,
    'ee': ee,
    'ge': ge,
    'te': p / q,
    'TE': (predation + M0 + net_growth + export) / inner_q,
    'gs': gs,
    'M0': M0,
    'egestion': egestion,
    'respiration': respiration,
    'export': export,
    'growth': net_growth,
    'ee': ee,
    'p_times_ee': p_times_ee,
    'inner_q': inner_q,
})
df.round(decimals=5)
# model_groups_data.round(decimals=5)

,q,p,test,test3,test4,predation,ee,ge,te,TE,gs,M0,egestion,respiration,export,growth,p_times_ee,inner_q
Detritus,0.00000,0.00000,0.00000,-17034.81551,-17034.81551,305.33891,0.01792,0.00000,NaN,inf,0.0,0.00000,0.00000,0.00000,0.00000,16729.4766,0.00000,0.00000
Phytoplankton,0.00000,919.34252,-919.34252,-0.00005,-0.00005,367.73706,0.40000,0.00000,inf,inf,0.0,551.60551,0.00000,0.00000,0.00000,0.0000,367.73701,0.00000
Benthic producers,0.00000,16324.55000,-16324.55000,0.02655,0.02655,129.37651,0.00793,0.00000,inf,inf,0.0,16195.14694,0.00000,0.00000,0.00000,0.0000,129.40306,0.00000
Zooplankton,363.86023,107.15625,0.00002,0.00001,0.00001,101.79843,0.95000,0.29450,0.29450,0.29450,0.4,5.35781,145.54409,111.15987,0.00000,0.0000,101.79844,363.86023
Other Fish,27.33101,5.46620,-0.00000,0.00000,0.00000,5.19289,0.95000,0.20000,0.20000,0.20000,0.2,0.27331,5.46620,16.39861,0.00000,0.0000,5.19289,27.33101
Benthos,431.25503,38.81295,60.37570,-0.00000,-0.00000,19.40648,0.50000,0.09000,0.09000,0.09000,0.2,19.40648,25.87530,306.19107,0.00000,0.0000,19.40648,431.25503
Molluscs,7.39004,1.10851,0.34742,-0.00000,-0.00000,0.83138,0.75000,0.15000,0.15000,0.15000,0.2,0.27713,1.13059,4.80352,0.00000,0.0000,0.83138,7.39004
Northern Shrimp,9.17355,1.83471,0.18347,0.00000,0.00000,1.74297,0.95000,0.20000,0.20000,0.20000,0.2,0.09174,1.65124,5.50413,0.00000,0.0000,1.74297,9.17355
Nephrops,0.43538,0.08708,0.01306,-0.00000,-0.00000,0.08268,0.95000,0.20000,0.20000,0.20000,0.2,0.00435,0.07402,0.26123,0.00004,0.0000,0.08272,0.43538
Other Pelagics,30.56259,4.58439,-0.00000,0.00000,0.00000,4.35326,0.95000,0.15000,0.15000,0.15000,0.2,0.22922,6.11252,19.86568,0.00191,0.0000,4.35517,30.56259
Capelin,27.31269,5.46254,0.00000,0.00000,0.00000,5.18938,0.95000,0.20000,0.20000,0.20000,0.2,0.27313,5.46254,16.38761,0.00003,0.0000,5.18941,27.31269
Herring,5.30769,1.06768,-0.00000,-0.00000,-0.00000,0.81445,0.95000,0.20116,0.20116,0.20116,0.2,0.05338,1.06154,3.17848,0.19985,0.0000,1.01429,5.30769
Other Dem. Fish,4.77485,0.71623,0.11997,0.00000,0.00000,0.58558,0.95000,0.15000,0.15000,0.15000,0.2,0.03581,0.83500,3.10365,0.09484,0.0000,0.68042,4.77485
Other Flatfish,2.30275,0.46055,0.00000,-0.00000,-0.00000,0.38371,0.95000,0.20000,0.20000,0.20000,0.2,0.02303,0.46055,1.38165,0.05381,0.0000,0.43752,2.30275
Greenland Halibut,1.65180,0.33036,-0.00000,-0.00000,-0.00000,0.31374,0.95000,0.20000,0.20000,0.20000,0.2,0.01652,0.33036,0.99108,0.00010,0.0000,0.31384,1.65180
Redfish,6.15857,1.23171,0.00000,-0.00000,-0.00000,0.83592,0.95000,0.20000,0.20000,0.20000,0.2,0.06159,1.23171,3.69514,0.33421,0.0000,1.17013,6.15857
Saithe,2.04017,0.40803,0.00041,-0.00000,-0.00000,0.21590,0.95000,0.20000,0.20000,0.20000,0.2,0.02040,0.40763,1.22410,0.17173,0.0000,0.38763,2.04017
Haddock,1.96981,0.39396,-0.00000,-0.00000,-0.00000,0.20041,0.95000,0.20000,0.20000,0.20000,0.2,0.01970,0.39396,1.18189,0.17386,0.0000,0.37426,1.96981
Juvenile Cod,1.34345,0.40303,0.00000,0.00000,0.00000,0.38288,0.95000,0.30000,0.30000,0.30000,0.2,0.02015,0.26869,0.67172,0.00000,0.0000,0.38288,1.34345
Adult Cod,6.16943,1.23389,0.00000,0.00000,0.00000,0.29768,0.95000,0.20000,0.20000,0.20000,0.2,0.06169,1.23389,3.70166,0.87451,0.0000,1.17219,6.16943
Seabirds,2.03484,0.00929,0.02775,0.00000,0.00000,0.00883,0.95000,0.00457,0.00457,0.00457,0.2,0.00046,0.37922,1.61858,0.00000,0.0000,0.00883,2.03484
Pinnipeds,1.98270,0.00696,0.00000,0.00000,0.00000,0.00562,0.95000,0.00351,0.00351,0.00351,0.2,0.00035,0.39654,1.57920,0.00100,0.0000,0.00661,1.98270
Baleen whales,11.51778,0.04850,-0.00000,0.00000,0.00000,0.00440,0.95000,0.00421,0.00421,0.00421,0.2,0.00242,2.30356,9.16572,0.04168,0.0000,0.04607,11.51778
Toothed whales,0.52548,0.00166,0.00000,0.00000,0.00000,0.00079,0.95000,0.00316,0.00316,0.00316,0.2,0.00008,0.10510,0.41872,0.00079,0.0000,0.00158,0.52548

In [86]:
df2 = pd.DataFrame({
    'test': q - (p + egestion + respiration),  # should be 0
    'test_r': (q - (p + egestion + respiration)) / q,  # small relative error
    'test2': q - (predation + M0 + net_growth + egestion + respiration),
    'test2_r': (q - (predation + M0 + net_growth + egestion + respiration)) / q,  # mostly small relative error
    'test3': p - (predation + M0 + net_growth + export),
    'test3_r': (p - (predation + M0 + net_growth + export)) / p,  # high relative error
    'test4': p_times_ee - predation,  # should be 0
    'test4_r': (p_times_ee - predation) / p_times_ee,  # high should be 0
})
df2.round(decimals=5)

,test,test_r,test2,test2_r,test3,test3_r,test4,test4_r
group_seq,,,,,,,,
Detritus,0.00000,NaN,-17034.81551,-inf,-17034.81551,-inf,-305.33891,-inf
Phytoplankton,-919.34252,-inf,-919.34257,-inf,-0.00005,-0.0,-0.00005,-0.00000
Benthic producers,-16324.55000,-inf,-16324.52345,-inf,0.02655,0.0,0.02655,0.00021
Zooplankton,0.00002,0.00000,0.00003,0.00000,0.00001,0.0,0.00001,0.00000
Other Fish,-0.00000,-0.00000,-0.00000,-0.00000,0.00000,0.0,0.00000,0.00000
Benthos,60.37570,0.14000,60.37570,0.14000,-0.00000,-0.0,-0.00000,-0.00000
Molluscs,0.34742,0.04701,0.34742,0.04701,-0.00000,-0.0,-0.00000,-0.00000
Northern Shrimp,0.18347,0.02000,0.18347,0.02000,0.00000,0.0,0.00000,0.00000
Nephrops,0.01306,0.03000,0.01310,0.03010,-0.00000,-0.0,0.00004,0.00051
Other Pelagics,-0.00000,-0.00000,0.00191,0.00006,0.00000,0.0,0.00191,0.00044
Capelin,0.00000,0.00000,0.00003,0.00000,0.00000,0.0,0.00003,0.00001
Herring,-0.00000,-0.00000,0.19985,0.03765,-0.00000,-0.0,0.19985,0.19703
Other Dem. Fish,0.11997,0.02513,0.21481,0.04499,0.00000,0.0,0.09484,0.13938
Other Flatfish,0.00000,0.00000,0.05381,0.02337,-0.00000,-0.0,0.05381,0.12299
Greenland Halibut,-0.00000,-0.00000,0.00010,0.00006,-0.00000,-0.0,0.00010,0.00031
Redfish,0.00000,0.00000,0.33421,0.05427,-0.00000,-0.0,0.33421,0.28561
Saithe,0.00041,0.00020,0.17214,0.08438,-0.00000,-0.0,0.17173,0.44303
Haddock,-0.00000,-0.00000,0.17386,0.08826,-0.00000,-0.0,0.17386,0.46453
Juvenile Cod,0.00000,0.00000,0.00000,0.00000,0.00000,0.0,0.00000,0.00000
Adult Cod,0.00000,0.00000,0.87451,0.14175,0.00000,0.0,0.87451,0.74605
Seabirds,0.02775,0.01364,0.02775,0.01364,0.00000,0.0,0.00000,0.00000
Pinnipeds,0.00000,0.00000,0.00100,0.00050,0.00000,0.0,0.00100,0.15055
Baleen whales,-0.00000,-0.00000,0.04168,0.00362,0.00000,0.0,0.04168,0.90457
Toothed whales,0.00000,0.00000,0.00079,0.00150,0.00000,0.0,0.00079,0.49934

In [2]:
Z

,1,2,3,4,5,6,7,8,9,10,...,14,15,16,17,18,19,20,21,23,24
1,0.000789,0.003794,0.003794,0.003794,0.015531,0.015531,0.015531,0.015531,0.047767,0.015531,...,0.018599,0.015531,0.010999,0.010999,0.253672,0.010999,0.015531,0.001897,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.082644,0.082644,0.082644,0.082644,0.165287,0.082644,...,0.454540,0.082644,0.057851,0.110192,0.165287,0.110192,0.082644,9.256093,0.000000,0.000000
3,0.000000,0.000603,0.001822,0.005033,0.085104,0.085104,0.060227,0.085104,0.013926,0.085104,...,0.222818,0.085104,0.004040,0.190324,0.236745,0.190324,0.085104,0.153188,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.913767,0.032370,0.000000,0.000000,0.000000,0.685326,0.091377,0.161852,0.000000,0.138730
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.032795,0.021604,0.032619,0.064685,0.033813,...,1.825602,0.351594,0.000000,0.750524,0.000000,0.743758,0.574728,1.386099,0.000000,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.201517,0.000000,0.550814,0.094041,0.362731,0.134345,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.005909,0.000000,...,0.196981,0.000000,0.000000,0.068943,0.000000,1.047940,0.025608,0.610642,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.002040,0.020402,0.000000,0.020402,0.000000,...,0.591649,0.002040,0.000000,0.000000,0.000000,0.163214,0.530444,0.701818,0.000000,0.002040
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.030793,0.000000,0.000000,0.000000,0.000000,...,0.184757,0.123171,0.000000,0.080061,0.000000,0.923785,0.246343,4.569657,0.000000,0.000000
10,0.000000,0.000000,0.000000,0.000000,0.089403,0.059320,0.000000,0.000000,0.260961,0.096652,...,0.471180,0.118640,0.000000,0.079094,0.025705,0.033615,0.158187,0.001977,0.000000,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.026168,0.000000,0.000000,0.157006,0.000000,...,0.096820,0.000000,0.000000,0.086353,0.000000,1.308383,0.523353,0.104671,0.000000,0.000000
12,0.000000,0.000000,0.000000,0.000000,0.024998,0.048488,0.000000,0.000000,0.099979,0.000000,...,0.184957,0.000000,0.002389,0.164965,0.149970,2.289500,0.999782,0.199957,0.000000,0.599869
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.776925,0.530769,0.000000
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,24.581418,2.731269,0.000000
15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.771613,0.000000,0.000000,0.000000,5.786868,0.462931,23.510985,0.000000,0.000000
16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.130615,0.000000,0.217692,0.021769,0.065307
17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,2.752065,0.000000,5.045452,0.458677,0.917355
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.007402,0.000000,0.000000,1.737091,1.302818,2.605637,0.000000,1.737091
19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,129.376508,301.878518
20,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.027706,2.770555,0.000000,0.000000,0.000000,0.941990,0.000000,23.549740,0.000000,0.000000
21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,363.860228,0.000000
23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,0.105178,2.305981,0.396888,0.407433,1.295580,0.288842,0.413661,0.428436,1.293299,0.346879,...,5.735664,6.341738,0.091430,1.926445,1.755134,105.657482,5.739512,150.901903,16746.752452,NaN

# Northen Gulf of Saint Lawrence

In [68]:
model_number = 116  # Northern Gulf Od Saint Lawrence #1
# model_number = 462  # Northern Gulf Od Saint Lawrence #2

seq2name = get_seq2name(model_number)
model_groups_data = get_model_groups_data(model_number)
DC, det_fate = get_DC(model_number)

# flow to det:
# flow_from_food = model_groups_data["biomass"] * model_groups_data["qb"] * model_groups_data["prop_unassimilated_food"] * (DC * (1-det_fate)).sum(axis=1)
flow_from_food = model_groups_data["biomass"] * model_groups_data["qb"] * model_groups_data["prop_unassimilated_food"]
flow_from_bodies = model_groups_data["biomass"] * model_groups_data["M0b"]
model_groups_data['M0'] = flow_from_bodies
model_groups_data['flow_to_det'] = flow_from_food + flow_from_bodies

net_growth = model_groups_data['export'] + model_groups_data['biomass_accum'] + model_groups_data['emigration']
model_groups_data['net_growth'] = net_growth
respiration = model_groups_data['respiration']
production = model_groups_data['p']

# model_groups_data['p'].sort_index()
model_groups_data.sort_index()
# resipiration2 = model_groups_data['q'] * (1-model_groups_data['prop_unassimilated_food']) - model_groups_data['p']
# model_groups_data['r2'] = resipiration2
# model_groups_data[['r2', 'respiration']]

# get Z:
# Z = get_Z(model_number, use_det_fate=False)
# Z.rename(columns=seq2name).T  # should be like in the article

# # combine PP to single row:
# PP_seq_list = model_groups_data.index[model_groups_data['trophic_info'] == 'PP'].values
# PP_seq = PP_seq_list[-1]
# if len(PP_seq_list) > 1:
#     Z, net_growth, respiration, production = merge_pp([Z, net_growth, respiration, production], PP_seq_list)

# DET_seq = model_groups_data[model_groups_data['trophic_info'] == 'DET'].index.values[0]

# # combine part of DET that is PP into PP row:
# Z_without_DET = Z.copy()
# percent_of_det_that_is_PP = Z_without_DET.loc[DET_seq, PP_seq] / Z_without_DET.loc[DET_seq, :].sum()  # 98%
# Z_without_DET.loc[:, PP_seq] += percent_of_det_that_is_PP * Z_without_DET.loc[:, DET_seq]
# Z_without_DET = Z_without_DET.drop(index=DET_seq, columns=DET_seq)

# # production of living compartments:
# P = production.add(net_growth, fill_value=0)
# if isinstance(P, pd.DataFrame):
#     P = P.sum(axis=1)
# non_PP = model_groups_data['trophic_info'] == 'Regular'
# ee = model_groups_data[non_PP]["ee"]
# export = -model_groups_data[non_PP]["export"]
# P[non_PP] = P[non_PP].add(export).mul(ee)
# P = P.drop(index=DET_seq).sort_index(ascending=False).rename(index=seq2name)

# # production-normalized transaction matrix:
# A = Z_without_DET.T.sort_index(ascending=False).sort_index(axis=1, ascending=False).rename(index=seq2name, columns=seq2name) / P

# # production requirement matrix:
# seq_to_drop = P.index[P == 0]
# A = A.drop(columns=seq_to_drop, index=seq_to_drop)
# L = pd.DataFrame(np.linalg.inv((np.identity(A.shape[0]) - A)), index=A.index, columns=A.columns)

# L

,group_name,trophic_info,export,tl,biomass,pb,qb,p,q,respiration,...,prop_unassimilated_food,ee,M0b,flow_to_det,biomass_accum,biomass_accum_rate,emigration,immigration,M0,net_growth
group_seq,,,,,,,,,,,,,,,,,,,,,
1,Cetacea,Regular,0.000400,4.093985,0.120000,0.072643,7.265048,0.008717,0.871806,0.775908,...,0.100,0.045886,0.069310,0.095498,0.0,0.0,0.0,0.0,0.008317,0.000400
2,Harp seals,Regular,0.004200,4.247342,0.042961,0.102909,10.291240,0.004421,0.442121,0.305063,...,0.300,0.950000,0.005145,0.132857,0.0,0.0,0.0,0.0,0.000221,0.004200
3,Hooded seals,Regular,0.000010,4.857662,0.003292,0.053410,9.658946,0.000176,0.031800,0.022084,...,0.300,0.056870,0.050372,0.009706,0.0,0.0,0.0,0.0,0.000166,0.000010
4,Grey seals,Regular,0.000700,4.516014,0.013000,0.109341,10.933355,0.001421,0.142134,0.098072,...,0.300,0.492459,0.055495,0.043362,0.0,0.0,0.0,0.0,0.000721,0.000700
5,Harbour seals,Regular,0.000000,4.158625,0.002000,0.070937,7.091081,0.000142,0.014182,0.009786,...,0.300,0.000000,0.070937,0.004397,0.0,0.0,0.0,0.0,0.000142,0.000000
6,Seabirds,Regular,0.000300,4.141750,0.002600,0.401664,42.050556,0.001044,0.109331,0.075488,...,0.300,0.287266,0.286280,0.033544,0.0,0.0,0.0,0.0,0.000744,0.000300
7,Large cod,Regular,0.694000,4.229020,2.009000,0.826202,2.757616,1.659840,5.540050,2.218195,...,0.300,0.449252,0.455029,2.576169,0.0,0.0,0.0,0.0,0.914154,0.694000
8,Small cod,Regular,0.000900,3.595177,0.820000,0.819911,4.032117,0.672327,3.306336,1.642108,...,0.300,0.809393,0.156280,1.120051,0.0,0.0,0.0,0.0,0.128150,0.000900
9,Large Green. halibut,Regular,0.039500,4.007891,0.310000,0.159938,1.599346,0.049581,0.495797,0.297478,...,0.300,0.951906,0.007692,0.151124,0.0,0.0,0.0,0.0,0.002385,0.039500
10,Small Green. halibut,Regular,0.000000,3.998634,0.480000,0.230284,2.302753,0.110536,1.105321,0.884253,...,0.100,0.687471,0.071970,0.145078,0.0,0.0,0.0,0.0,0.034546,0.000000
11,American plaice,Regular,0.018300,3.502715,1.060000,0.384549,1.281830,0.407622,1.358740,0.543496,...,0.300,0.692165,0.118378,0.533102,0.0,0.0,0.0,0.0,0.125480,0.018300
12,Flounders,Regular,0.008100,3.116166,0.840000,0.301472,1.004897,0.253236,0.844114,0.337643,...,0.300,0.942393,0.017367,0.267822,0.0,0.0,0.0,0.0,0.014588,0.008100
13,Skates,Regular,0.000000,3.927148,0.230000,0.203271,2.032689,0.046752,0.467519,0.280511,...,0.300,0.961775,0.007770,0.142043,0.0,0.0,0.0,0.0,0.001787,0.000000
14,Redfish,Regular,0.290000,3.585792,7.160000,0.236698,1.689643,1.694757,12.097847,6.773735,...,0.300,0.949672,0.011913,3.714648,0.0,0.0,0.0,0.0,0.085294,0.290000
15,Large demersals,Regular,0.010200,3.791716,0.940000,0.160052,1.037133,0.150449,0.974905,0.531985,...,0.300,0.733198,0.042702,0.332612,0.0,0.0,0.0,0.0,0.040140,0.010200
16,Small demersals,Regular,0.000000,3.098132,0.970000,0.465242,1.550825,0.451285,1.504300,0.601726,...,0.300,0.943119,0.026463,0.476960,0.0,0.0,0.0,0.0,0.025670,0.000000
17,Capelin,Regular,0.027200,3.234585,9.520000,0.959449,3.198032,9.133951,30.445265,18.266787,...,0.100,0.949128,0.048809,3.509187,0.0,0.0,0.0,0.0,0.464661,0.027200
18,Sand lance,Regular,0.000000,3.128618,1.140000,1.089154,8.072308,1.241635,9.202431,5.807426,...,0.234,0.946941,0.057789,2.219249,0.0,0.0,0.0,0.0,0.065880,0.000000
19,Arctic cod,Regular,0.000000,3.349314,0.020000,0.531340,1.771066,0.010627,0.035421,0.021252,...,0.100,0.898883,0.053728,0.004617,0.0,0.0,0.0,0.0,0.001075,0.000000
20,Large pelagics,Regular,0.001500,3.864730,0.040000,0.250748,1.441931,0.010030,0.057677,0.041880,...,0.100,0.712070,0.072198,0.008656,0.0,0.0,0.0,0.0,0.002888,0.001500
21,Pisci. small pelagics,Regular,0.023500,3.130912,2.120000,0.319007,1.160942,0.676295,2.461197,1.046542,...,0.300,0.691504,0.098413,0.946994,0.0,0.0,0.0,0.0,0.208635,0.023500
22,Plank. small pelagics,Regular,0.211000,3.092282,1.550000,0.479000,1.628857,0.742450,2.524729,1.024860,...,0.300,0.946428,0.025661,0.797193,0.0,0.0,0.0,0.0,0.039775,0.211000
23,Shrimp,Regular,0.083100,2.265897,0.680000,1.933326,6.444493,1.314662,4.382255,2.629368,...,0.100,0.951503,0.093760,0.501983,0.0,0.0,0.0,0.0,0.063757,0.083100
24,Large crustacea,Regular,0.042200,3.077945,1.590000,0.298344,1.356590,0.474366,2.156977,1.466913,...,0.100,0.401243,0.178635,0.499728,0.0,0.0,0.0,0.0,0.284030,0.042200
25,Echinoderms,Regular,0.000000,2.000000,81.900000,0.410240,1.367467,33.598660,111.995542,44.798220,...,0.300,0.023208,0.400719,66.417580,0.0,0.0,0.0,0.0,32.818918,0.000000
26,Molluscs,Regular,0.034500,2.000000,53.440000,0.429482,4.772024,22.951529,255.016963,155.560349,...,0.300,0.021800,0.420120,98.956278,0.0,0.0,0.0,0.0,22.451189,0.034500
27,Polychaetes,Regular,0.000000,2.154734,14.820000,2.110523,7.703680,31.277944,114.168538,71.473740,...,0.100,0.548069,0.953811,25.552329,0.0,0.0,0.0,0.0,14.135475,0.000000
28,Other ben. inver.,Regular,0.000000,2.000000,5.700000,1.609362,5.364541,9.173364,30.577881,12.231153,...,0.300,0.327186,1.082801,15.345332,0.0,0.0,0.0,0.0,6.171967,0.000000
29,Large zooplankton,Regular,0.000000,2.418964,14.680000,2.629147,19.956997,38.595878,292.968714,107.888481,...,0.500,0.543619,1.199893,164.098786,0.0,0.0,0.0,0.0,17.614429,0.000000
30,Small zooplankton,Regular,0.000000,2.102536,71.860000,4.815014,19.260055,346.006906,1384.027588,408.288147,...,0.455,0.794766,0.988206,700.745038,0.0,0.0,0.0,0.0,71.012485,0.000000
31,Phytoplankton,PP,0.000000,1.000000,12.950000,105.034943,0.000000,1360.202512,0.000000,0.000000,...,0.000,0.857165,15.002677,194.284662,0.0,0.0,0.0,0.0,194.284662,0.000000
32,Detritus,DET,0.269226,1.000000,132.610000,NaN,NaN,NaN,NaN,0.000000,...,0.000,0.999651,-3.490651,NaN,0.0,0.0,0.0,0.0,-462.895216,0.269226