In [1]:
import os
import sys

# Standard interactive replacement for the 'parent directory' hack
parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.append(parent_dir)

import pandas as pd
import numpy as np
from tqdm import tqdm
from pathlib import Path

from PPRCalculator import PPRCalculator
from ModelData import ModelData

In [2]:
# model_path = f'../real_models/EwE_jsons/168_168_Greenland,_West_Coast_(1997).json'
# model_path = f'../real_models/EwE_validation/18_168_Greenland,_West_Coast_(1997).json'

model_path = f'../real_models/EwE_jsons/680_680_North_Sea_(1981).json'
# model_path = f'../real_models/EwE_validation/22_680_North_Sea_(1981).json'  # only one with >> 1% error in ppr/npp (20% error). original article has biomass accum data that we ignore.

# model_path = f'../real_models/EwE_jsons/486_486_Cape_Verde_(1981).json'
# model_path = f'../real_models/EwE_validation/27_486_Cape_Verde_(1981-1985).json'

# model_path = f'../real_models/EwE_jsons/651_651_Mauritania_(1998).json'
# model_path = f'../real_models/EwE_validation/27_651_Mauritania_(1998).json'

# model_path = f'../real_models/EwE_jsons/646_646_Guinea_(1998).json' 
# model_path = f'../real_models/EwE_validation/28_646_Guinea_(1998).json'  # another one with >> 1% error in ppr/npp (300% error). diet composition is different between versions.

# model_path = f'../real_models/EwE_jsons/46_46_Denmark,_Faroe_Islands_(1997).json'
# model_path = f'../real_models/EwE_validation/59_46_Denmark,_Faroe_Islands_(1997).json'

# model_path = f'../real_models/EwE_validation/22_680_North_Sea_(1980).json'

model = ModelData(model_path)
self = PPRCalculator.from_modeldata(model, underdetermined=True, zero_biomass_accum=False, default_gs=True, weight_flow=1.0, weight_guess=1.0)
# self = PPRCalculator.from_modeldata(model, underdetermined=True, zero_biomass_accum=False, default_gs=True)
self.get_groups_df().round(5)

,group_name,trophic_info,taxon_descr,tl,ge,ee,catch,biomass,pb,qb,...,gs,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import,det_export
group_seq,,,,,,,,,,,,,,,,,,,,,
30,diet_import,Import,NaN,1.00000,1.00000,1.00000,0.000,1.00000,0.00000,0.00000,...,0.0,0.00000,0.00000,0.00000,0.0,0.0,0.0,0.00000,0.0,0.0
29,Detritus,DET,None,1.00000,1.00000,1.00000,0.000,50.00000,97.92396,97.92396,...,0.0,0.00000,0.00000,20.85523,0.0,0.0,0.0,0.00000,0.0,0.0
28,PT pico,Regular,None,2.00000,0.40000,0.95000,0.000,1.40123,1000.00000,2500.00000,...,0.3,1050.92159,1050.92163,0.00000,0.0,0.0,0.0,1120.98303,0.0,0.0
27,PS pico,PP,None,1.00000,1.00000,0.95000,0.000,0.93415,1000.00000,1000.00000,...,0.0,0.00000,0.00000,0.00000,0.0,0.0,0.0,46.70763,0.0,0.0
26,PT nano,Regular,None,2.60000,0.40000,0.95000,0.000,4.43722,200.00000,500.00000,...,0.3,665.58366,665.58370,0.00000,0.0,0.0,0.0,709.95590,0.0,0.0
25,PS nano,PP,None,1.00000,1.00000,0.95000,0.000,2.95815,200.00000,200.00000,...,0.0,0.00000,0.00000,0.00000,0.0,0.0,0.0,29.58149,0.0,0.0
24,PT micro,Regular,None,2.96000,0.40000,0.95000,0.000,10.50558,53.50000,133.75000,...,0.3,421.53628,421.53626,0.00000,0.0,0.0,0.0,449.63870,0.0,0.0
23,PS micro,PP,None,1.00000,1.00000,0.23210,0.000,43.00000,53.50000,53.50000,...,0.0,0.00000,0.00000,0.00000,0.0,0.0,0.0,1766.55407,0.0,0.0
22,O.invertebrates,Regular,None,2.73220,0.15000,0.95000,0.000,12.94883,3.00000,20.00000,...,0.2,51.79532,168.33481,0.00000,0.0,0.0,0.0,53.73765,0.0,0.0
21,O.macrobenthos,Regular,None,2.39200,0.15000,0.69510,0.000,49.00000,2.00000,13.33333,...,0.2,130.66666,424.66663,0.00000,0.0,0.0,0.0,160.54648,0.0,0.0
20,Polychaeta,Regular,None,2.00000,0.15000,0.72876,0.000,32.00000,2.00000,13.33333,...,0.2,85.33333,277.33330,0.00000,0.0,0.0,0.0,102.69244,0.0,0.0
19,Echinodermata,Regular,None,2.19600,0.15000,0.77976,0.000,24.00000,2.00000,13.33333,...,0.2,64.00000,208.00000,0.00000,0.0,0.0,0.0,74.57138,0.0,0.0
18,O.crustaceans,Regular,None,2.47340,0.15000,0.95000,0.000,15.81093,3.00000,20.00000,...,0.2,63.24370,205.54202,0.00000,0.0,0.0,0.0,65.61534,0.0,0.0
17,Euphausiacea,Regular,None,3.84548,0.15000,0.95000,0.000,9.14853,2.43000,16.20000,...,0.2,29.64125,96.33405,0.00000,0.0,0.0,0.0,30.75280,0.0,0.0
16,Copepoda,Regular,None,2.93100,0.30000,0.97693,0.000,10.00000,18.00000,60.00000,...,0.4,240.00000,180.00000,0.00000,0.0,0.0,0.0,244.15337,0.0,0.0
15,Juvenile fish,Regular,None,3.86536,0.20000,0.95000,0.000,1.94977,5.00000,25.00000,...,0.2,9.74884,29.24651,0.00000,0.0,0.0,0.0,10.23628,0.0,0.0
14,O.prey fish,Regular,None,2.97122,0.13562,0.95000,0.000,4.34600,0.47468,3.50000,...,0.2,3.04220,10.10582,0.00000,0.0,0.0,0.0,3.14535,0.0,0.0
13,O.pred.fish,Regular,None,4.48461,0.15000,0.00000,0.000,1.47500,0.86850,5.79000,...,0.2,1.70805,5.55116,0.00000,0.0,0.0,0.0,2.98909,0.0,0.0
12,Ray,Regular,None,3.80506,0.15000,0.00000,0.000,0.52800,0.43500,2.90000,...,0.2,0.30624,0.99528,0.00000,0.0,0.0,0.0,0.53592,0.0,0.0
11,Sole,Regular,None,3.03920,0.15000,0.49841,0.025,0.07600,0.66000,4.40000,...,0.2,0.06688,0.21736,0.00000,0.0,0.0,0.0,0.09204,0.0,0.0
10,Plaice,Regular,None,3.17122,0.23214,0.53292,0.221,0.63800,0.65000,2.80000,...,0.2,0.35728,1.01442,0.00000,0.0,0.0,0.0,0.55098,0.0,0.0
9,Sandeel,Regular,None,3.71612,0.15000,0.58356,1.158,2.57700,2.02000,13.46667,...,0.2,6.94072,22.55734,0.00000,0.0,0.0,0.0,9.10850,0.0,0.0
8,Norway pout,Regular,None,4.43771,0.15000,0.49485,0.805,1.94100,2.48000,16.53333,...,0.2,6.41824,20.85928,0.00000,0.0,0.0,0.0,8.84987,0.0,0.0
7,Sprat,Regular,None,3.79372,0.14070,0.96087,0.343,0.54500,1.21000,8.60000,...,0.2,0.93740,3.09015,0.00000,0.0,0.0,0.0,0.96321,0.0,0.0
6,Herring,Regular,None,4.50883,0.22609,0.54430,0.293,0.83600,1.04000,4.60000,...,0.2,0.76912,2.20704,0.00000,0.0,0.0,0.0,1.16533,0.0,0.0
5,Haddock,Regular,None,3.81793,0.36186,0.64553,0.381,0.83200,1.37000,3.78600,...,0.2,0.62999,1.38012,0.00000,0.0,0.0,0.0,1.03403,0.0,0.0
4,Mackerel,Regular,None,4.46760,0.05009,0.83234,0.112,0.46400,0.29000,5.79000,...,0.2,0.53731,2.01469,0.00000,0.0,0.0,0.0,0.55987,0.0,0.0
3,Saithe,Regular,None,5.07009,0.17651,0.54127,0.205,0.65300,0.58000,3.28600,...,0.2,0.42915,1.33787,0.00000,0.0,0.0,0.0,0.60289,0.0,0.0
2,Whiting,Regular,None,4.47844,0.23609,0.94914,0.367,0.65700,0.84000,3.55800,...,0.2,0.46752,1.31820,0.00000,0.0,0.0,0.0,0.49559,0.0,0.0
1,Cod,Regular,None,4.12914,0.35205,0.96831,0.572,0.56900,1.11000,3.15300,...,0.2,0.35881,0.80366,0.00000,0.0,0.0,0.0,0.37883,0.0,0.0

In [191]:
report = self.diagnose_sppr(
    TE_option='GE',
    short=False,
    flat=False
)
# report['warnings']
# report['config']
# report['model_input']
# report['divergence']
# report['balance']
report['footprint']

{'ppr_all': 1144.0468523075951,
 'ppr_inner': 1144.0361512497998,
 'ppr_pp_only': 457.88816119741483,
 'npp': 4116.0,
 'ppr2npp': 0.2779485304299805,
 'ppr2npp_pp_only': 0.11124590894009107}

In [192]:
report['model_input']

{'status': 'OK',
 'is_model_balanced': True,
 'p_max_rel_residual': 9.051424625991331e-08,
 'q_max_rel_residual': 9.453343315609422e-08,
 'dc_rows_sum_to_1': True,
 'dc_max_deviation': 5.029999994299317e-08,
 'n_negative_catch': 0,
 'n_zero_catch': 17,
 'total_catch': 0.8679521626500001,
 'has_catch': True,
 'has_ee_issues': False,
 'n_ee0': 0,
 'n_ee_marginal': 0,
 'n_ee_gt_1': 0,
 'ee0_groups': [],
 'ee_marginal_groups': []}

In [193]:
report['divergence']

{'status': 'OK',
 'solve_error': None,
 'b': 0.35481349180790606,
 'b_converges': True,
 'rho_living': 0.4497225471690407,
 'living_converges': True,
 'sppr_det': {44: 1.7792128894394235},
 'max_sppr_det': 1.7792128894394235,
 'max_sppr_group': {'seq': 2,
  'tl': 4.656980876328685,
  'sppr': 102666.44680185537,
  'inv_te': 173.08198428571427},
 'max_tl_group': {'seq': 2,
  'tl': 4.656980876328685,
  'sppr': 102666.44680185537,
  'inv_te': 173.08198428571427},
 'n_negative_sources': 0,
 'expect_negatives': False,
 'near_singular_te': []}

In [50]:
report['balance']

{'status': 'OK',
 'is_balanced': True,
 'inflow': 3852.0,
 'outflow': 3852.000000000001,
 'rel_gap': 2.3610973566275395e-16}

In [211]:
self.get_DC().rename(index=self.seq2name, columns=self.seq2name).round(3)
# df1 = self.get_DC().round(3)

,diet_import,Detritus,Producteurs primaires,Zool P,Zool G,Benthos,Crustaces,Cephalopodes,Mesopelagiques,Bathy PM inv,...,Thons mineurs,Thons majeurs,Selaciens M cotiers,Selaciens M prof,Selaciens G cotiers,Selaciens G prof,Oiseaux,Tortues,Dauphins,Baleines
diet_import,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Detritus,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Producteurs primaires,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Zool P,0.000,0.100,0.900,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Zool G,0.000,0.100,0.100,0.780,0.020,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Benthos,0.000,0.800,0.030,0.150,0.000,0.020,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Crustaces,0.000,0.250,0.000,0.100,0.100,0.500,0.050,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Cephalopodes,0.000,0.000,0.000,0.000,0.056,0.074,0.567,0.019,0.074,0.037,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Mesopelagiques,0.000,0.000,0.000,0.599,0.204,0.177,0.020,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Bathy PM inv,0.000,0.000,0.000,0.080,0.317,0.395,0.108,0.000,0.100,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Bathy P pred,0.000,0.000,0.000,0.100,0.150,0.212,0.110,0.000,0.328,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Bathy G pred,0.000,0.000,0.000,0.081,0.249,0.020,0.249,0.125,0.114,0.051,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Dem P inv,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Dem P pred,0.000,0.040,0.000,0.000,0.020,0.270,0.240,0.000,0.000,0.057,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Dem M inv,0.000,0.016,0.044,0.058,0.070,0.640,0.153,0.020,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Dem M pred,0.000,0.000,0.000,0.000,0.000,0.166,0.315,0.129,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Dem G inv,0.000,0.175,0.000,0.200,0.000,0.375,0.250,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Dem G pred,0.000,0.000,0.000,0.000,0.031,0.370,0.142,0.031,0.082,0.010,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Cotiers P inv,0.000,0.000,0.268,0.261,0.010,0.358,0.094,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Capitaine royal,0.000,0.000,0.000,0.000,0.000,0.000,0.536,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Cotiers P pred,0.000,0.000,0.000,0.166,0.000,0.124,0.289,0.124,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Cotiers M inv,0.000,0.000,0.090,0.000,0.059,0.657,0.194,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Petit capitaine,0.000,0.000,0.000,0.000,0.000,0.166,0.745,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Mulets,0.000,0.285,0.488,0.108,0.107,0.010,0.001,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Disques,0.000,0.000,0.000,0.000,0.000,0.335,0.503,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Machoirons,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Cotier M pred,0.000,0.167,0.000,0.000,0.000,0.080,0.332,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Cotier P pred,0.000,0.000,0.000,0.003,0.002,0.163,0.309,0.097,0.000,0.000,...,0.000,0.000,0.000,0.000,0.005,0.00,0,0.010,0.000,0.000
Gros capitaine,0.000,0.000,0.000,0.000,0.000,0.000,0.505,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Bars,0.000,0.000,0.000,0.000,0.021,0.041,0.731,0.021,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Pel P inv,0.000,0.020,0.102,0.505,0.223,0.030,0.000,0.000,0.101,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Pel G pred,0.000,0.000,0.000,0.057,0.000,0.000,0.355,0.047,0.024,0.047,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Ethmalose,0.000,0.000,0.500,0.400,0.000,0.100,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Cotiers Pel P inv,0.000,0.190,0.213,0.233,0.166,0.090,0.070,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Cotiers Pel G pred,0.000,0.000,0.000,0.000,0.000,0.000,0.021,0.090,0.000,0.000,...,0.021,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Thons mineurs,0.000,0.000,0.000,0.040,0.030,0.030,0.020,0.194,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Thons majeurs,0.000,0.000,0.000,0.010,0.040,0.020,0.000,0.207,0.055,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Selaciens M cotiers,0.000,0.000,0.000,0.000,0.041,0.081,0.081,0.041,0.081,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Selaciens M prof,0.000,0.000,0.000,0.000,0.051,0.000,0.061,0.221,0.133,0.101,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Selaciens G cotiers,0.000,0.083,0.000,0.000,0.000,0.181,0.000,0.173,0.016,0.000,...,0.016,0.000,0.021,0.021,0.006,0.00,0,0.001,0.005,0.001
Selaciens G prof,0.000,0.005,0.004,0.000,0.023,0.014,0.210,0.164,0.015,0.056,...,0.010,0.021,0.000,0.010,0.000,0.02,0,0.000,0.005,0.001
Oiseaux,0.127,0.000,0.000,0.000,0.035,0.274,0.080,0.045,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Tortues,0.000,0.000,0.900,0.000,0.100,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Dauphins,0.000,0.000,0.000,0.000,0.000,0.051,0.000,0.687,0.133,0.031,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000
Baleines,0.000,0.000,0.000,0.000,0.755,0.000,0.000,0.038,0.044,0.022,...,0.000,0.000,0.000,0.000,0.000,0.00,0,0.000,0.000,0.000

In [206]:
self.get_DC().rename(index=self.seq2name, columns=self.seq2name).round(3)
df2 = self.get_DC().round(3)

In [207]:
df2 - df1

,45,44,43,42,41,40,39,38,37,36,...,10,9,8,7,6,5,4,3,2,1
45,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
44,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
43,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
42,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
41,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
40,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
39,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
38,0.000,0.000,0.000,0.000,0.056,-0.006,-0.044,-0.001,-0.009,-0.003,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
37,0.000,0.000,0.000,0.009,0.002,0.002,-0.003,-0.003,-0.005,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
36,0.000,0.000,0.000,0.004,-0.002,-0.002,-0.001,-0.001,0.002,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
35,0.000,0.000,0.000,-0.001,-0.001,-0.001,-0.001,0.000,-0.002,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
34,0.000,0.000,0.000,0.002,0.004,-0.004,0.004,0.002,0.002,0.002,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
33,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
32,0.000,-0.001,0.000,0.000,-0.004,0.001,0.001,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
31,0.000,0.000,0.000,-0.001,-0.001,-0.014,-0.003,0.020,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
30,0.000,0.000,-0.007,0.000,0.000,0.002,0.004,0.002,0.000,-0.003,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
29,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
28,0.000,0.000,-0.005,0.000,0.005,0.008,0.003,0.004,0.003,-0.003,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
27,-0.003,-0.009,0.011,0.012,-0.004,0.015,0.006,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
26,0.000,0.000,0.000,0.000,0.000,0.000,-0.001,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
25,0.000,0.000,0.000,-0.001,0.000,-0.001,-0.003,-0.001,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
24,0.000,0.000,0.000,0.000,0.000,0.001,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
23,0.000,0.000,0.000,0.000,0.000,-0.001,-0.005,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
22,0.000,0.001,0.001,0.000,0.000,-0.004,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
21,0.000,-0.071,-0.071,-0.071,-0.167,0.025,0.193,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
20,0.000,0.000,0.000,0.000,0.000,-0.333,-0.500,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
19,0.000,0.000,0.000,0.000,0.000,-0.003,-0.001,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
18,0.000,0.000,0.000,0.001,0.000,0.004,0.008,0.003,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,-0.004,0.0,0.0
17,0.000,0.000,0.000,0.000,0.000,0.000,0.005,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
16,0.000,-0.004,0.000,0.000,0.003,0.005,0.022,0.006,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
15,0.000,0.000,0.001,0.003,0.001,0.002,0.000,0.000,0.001,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
14,0.000,0.000,0.000,-0.003,0.000,0.000,-0.020,0.047,-0.001,-0.003,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
13,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
12,0.000,0.000,0.000,0.000,0.000,0.004,-0.001,0.000,-0.003,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
11,0.000,-0.002,0.000,-0.001,-0.001,-0.005,0.000,0.003,0.000,0.000,...,0.001,0.000,-0.003,0.000,0.0,0.000,0.0,0.000,0.0,0.0
10,0.000,0.000,0.000,0.004,0.003,0.003,0.002,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
9,0.000,0.000,0.000,0.000,0.002,0.003,-0.002,0.002,0.001,-0.005,...,0.000,0.000,0.000,-0.001,0.0,0.000,0.0,0.000,0.0,0.0
8,0.000,0.000,0.000,0.000,0.003,0.004,0.004,0.003,0.004,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
7,0.000,0.000,0.000,0.000,-0.003,-0.001,-0.001,0.002,0.001,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
6,0.000,0.000,0.000,0.000,-0.007,0.006,0.000,0.005,0.001,-0.003,...,0.001,-0.001,0.001,0.001,0.0,-0.006,0.0,0.000,0.0,0.0
5,0.000,0.000,0.000,0.000,0.000,0.000,0.002,0.001,0.000,0.000,...,-0.003,0.000,-0.004,0.000,0.0,0.000,0.0,0.000,0.0,0.0
4,-0.001,0.000,0.000,0.000,0.001,-0.002,0.001,0.001,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
3,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
2,0.000,0.000,0.000,0.000,0.000,0.003,0.000,0.014,0.003,0.005,...,-0.006,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0
1,0.000,0.000,0.000,0.000,0.002,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.000,0.0,0.0