In [1]:
import os
import sys

# Standard interactive replacement for the 'parent directory' hack
parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.append(parent_dir)

import pandas as pd
import numpy as np
from tqdm import tqdm

from PPRCalculator import PPRCalculator
from ModelData import ModelData

In [2]:
# model_path = '../real_models/EwE_jsons/227_Iceland_(1950).json'
model_path = '../real_models/EwE_jsons/10013_Humboldt_Current_(1995-2004).json'
# model_path = '../real_models/ToyModels/900_Multi_DET_Toy_(2026).json'
model = ModelData(model_path)
self = PPRCalculator.from_modeldata(model)

In [3]:
self.get_groups_df().loc[self.get_DET_seq(), :]

,group_name,trophic_info,taxon_descr,tl,ge,ee,catch,biomass,pb,qb,...,M0,gs,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import
group_seq,,,,,,,,,,,,,,,,,,,,,
36,Anchovy eggs,DET,None,NaN,1.0,1.0,0.0,0.44,186.557727,186.557727,...,0.0,0.0,0.0,0.0,12.720060,0.0,0.0,0.0,0.0,0.0
37,Fishery offal,DET,None,NaN,NaN,1.0,0.0,0.05,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
38,Pelagic detritus,DET,None,NaN,1.0,1.0,0.0,20.00,254.072118,254.072118,...,0.0,0.0,0.0,0.0,5081.442359,0.0,0.0,0.0,0.0,0.0
39,Benthic detritus,DET,None,NaN,1.0,1.0,0.0,60.00,29.149839,29.149839,...,0.0,0.0,0.0,0.0,-4342.711538,0.0,0.0,0.0,0.0,0.0

In [11]:
sppr, A, L = self.SPPR_new(TE=None, TE_option='TE', collapse_det=True)
sppr, A, L = PPRCalculator.rename_results([sppr, A, L], self.seq2name)
print(self.is_model_balanced()[0])
print(self.get_PPR(sppr).sum(axis=1))
print(f'balanced: {self.is_sppr_balanced(sppr)}')
sppr

True
catch    57.586634
dtype: float64
balanced: (True, np.float64(100.0), np.float64(100.0))

               diet_import  Slow detritus  Fast detritus  Phytoplankton
diet_import            1.0       0.000000       0.000000       0.000000
Slow detritus          0.0       0.625000       0.000000       0.000000
Fast detritus          0.0       0.000000       0.792079       0.000000
Detritivore            0.0       0.833333       4.224422       0.000000
Herbivore              0.0       0.000000       0.000000       4.166667
Phytoplankton          0.0       0.000000       0.000000       1.000000