In [1]:
import os
import sys

# Standard interactive replacement for the 'parent directory' hack
parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.append(parent_dir)

import pandas as pd
import numpy as np
from tqdm import tqdm

from PPRCalculator import PPRCalculator
from ModelData import ModelData

In [5]:
# model_path = '../real_models/EwE_jsons/227_Iceland_(1950).json'
model_path = '../real_models/EwE_jsons/10013_Humboldt_Current_(1995-2004).json'
# model_path = '../real_models/ToyModels/900_Multi_DET_Toy_(2026).json'
model = ModelData(model_path)
self = PPRCalculator.from_modeldata(model)

In [3]:
self.get_groups_df().loc[self.get_DET_seq(), :]

,group_name,trophic_info,taxon_descr,tl,ge,ee,catch,biomass,pb,qb,...,M0,gs,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import
group_seq,,,,,,,,,,,,,,,,,,,,,
36,Anchovy eggs,DET,None,NaN,1.0,1.0,0.0,0.44,186.557727,186.557727,...,0.0,0.0,0.0,0.0,12.720060,0.0,0.0,0.0,0.0,0.0
37,Fishery offal,DET,None,NaN,NaN,1.0,0.0,0.05,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
38,Pelagic detritus,DET,None,NaN,1.0,1.0,0.0,20.00,254.072118,254.072118,...,0.0,0.0,0.0,0.0,5081.442359,0.0,0.0,0.0,0.0,0.0
39,Benthic detritus,DET,None,NaN,1.0,1.0,0.0,60.00,29.149839,29.149839,...,0.0,0.0,0.0,0.0,-4342.711538,0.0,0.0,0.0,0.0,0.0

In [6]:
sppr, A, L = self.SPPR_new(TE=None, TE_option='GE', collapse_det=True)
sppr, A, L = PPRCalculator.rename_results([sppr, A, L], self.seq2name)
print(self.is_model_balanced()[0])
print(self.get_PPR(sppr).sum(axis=1))
print(f'balanced: {self.is_sppr_balanced(sppr)}')
sppr

False
catch    432.306908
dtype: float64
balanced: (False, np.float64(11311.556), np.float64(4814.485910899931))

,diet_import,Benthic detritus,Pelagic detritus,Fishery offal,Anchovy eggs,Dino/silicoflagellates,Diatoms
diet_import,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Benthic detritus,0.000000,5.831624,0.000000,0.000000,0.000000,0.000000,0.000000
Pelagic detritus,0.000000,0.000000,5.831624,0.000000,0.000000,0.000000,0.000000
Fishery offal,0.000000,0.000000,0.000000,5.831624,0.000000,0.000000,0.000000
Anchovy eggs,0.000000,0.000000,0.000000,0.000000,5.831624,0.000000,0.000000
Leatherback turtle,0.000000,68.451103,0.000000,0.000000,2.343811,6.795951,14.156773
Green sea turtle,1.000855,64.267373,0.000000,0.000000,1.310099,2.772707,5.783639
Cetaceans,53.033601,72887.849650,0.000000,0.000000,24.124394,6630.870918,14541.322078
Pinnipeds,90.994795,34033.906310,0.000000,0.000000,12.182927,2984.455644,7261.285418
Seabirds,65.372828,162159.779063,0.000000,0.000000,78.435190,15708.157907,35128.387024
Chondrichthyans,4.867076,3110.626331,0.000000,0.000000,0.755486,276.063939,610.955615
Catfish,12.042060,537.181487,0.000000,0.000000,0.050839,8.627939,19.306383
Sea robin,1.183715,168.249336,0.000000,0.000000,0.000000,12.527514,27.510105
Medium sciaenids,8.843411,587.484066,0.000000,0.000000,0.112713,26.527049,63.307723
Medium demersal fish,8.778290,437.479563,0.000000,0.000000,0.028321,11.170011,27.343634
Conger,27.038838,2397.623729,0.000000,0.000000,0.294361,139.316387,322.867120
Butter fishes,2.970983,147.789796,0.000000,0.000000,1.406075,3.654468,9.639776
Benthic elasmobranchs,11.242033,788.942575,0.000000,0.000000,0.122188,36.675272,85.216511
Small demersal fish,0.000000,41.298357,0.000000,0.000000,0.000000,4.457364,13.288777
Flatfish,23.143247,1469.593169,0.000000,0.000000,0.277498,59.171151,138.698421
Large hake,20.306009,3158.168741,0.000000,0.000000,0.705543,232.793936,525.637018
Medium hake,2.263545,711.236930,0.000000,0.000000,0.149894,62.618671,144.220612
Small hake,2.606801,682.170315,0.000000,0.000000,0.119439,56.337016,126.114368
Other large pelagic fish,0.828689,1037.548560,0.000000,0.000000,0.417288,98.362728,225.328281
Chub mackerel,0.430142,723.531582,0.000000,0.000000,0.320757,68.202155,152.292833
Horse mackerel,0.323467,471.637453,0.000000,0.000000,0.213414,43.077284,95.485505
Other small pelagic fish,0.500000,100.686633,0.000000,0.000000,0.000000,10.867188,25.648438
Other cephalopods,0.232558,42.656245,0.000000,0.000000,0.000000,3.552459,7.374874
Jumbo squid,0.572231,546.684700,0.000000,0.000000,0.038125,47.269622,99.980375
Mesopelagic fish,0.000000,194.469326,0.000000,0.000000,0.000000,16.671140,34.244111
Anchovy,0.000000,100.249501,0.000000,0.000000,0.061628,9.446602,21.307191
Sardine,0.000000,130.895825,0.000000,0.000000,0.049982,12.982128,27.160157
Macrobenthos,1.857143,68.313310,0.000000,0.000000,0.000000,0.000000,0.000000
Chrysaora plocamia,0.000000,62.905502,0.000000,0.000000,3.125081,6.392685,13.328918
Gelatinous zooplankton,0.000000,85.087905,0.000000,0.000000,0.000000,8.005748,16.640341
Macrozooplankton,0.000000,20.145171,0.000000,0.000000,0.000000,1.666274,3.413829
Mesozooplankton,0.000000,15.490251,0.000000,0.000000,0.000000,1.671875,3.484375
Microzooplankton,0.000000,33.045869,0.000000,0.000000,0.000000,1.733333,3.600000
Dino/silicoflagellates,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
Diatoms,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000